### ISSUE TITLE
Only the 10 first schedules are shown

### ISSUE THREAD

**Issue by cacyss0807** [SNUArduinoLabs/coe_control_center#16]
When trying to visualize all the schedules already created, it limits the view to 10. and since new schedules appear at the end of the list, after adding more than 10 schedules, it is not possible to visualize it , hence we cannot deploy it.

**Comment by zeronone** [comment]
coe_control_center/webapp/app/controllers/dashboard_controller.rb
Change `@schedules.order("ascending").limit(10)`     
Just search how to do ascending or descending order.

**Comment by cacyss0807** [comment]
:+1: thanks
