### ISSUE TITLE
Support for selection of all weekly days

### ISSUE THREAD

**Issue by cacyss0807** [SNUArduinoLabs/coe_control_center#3]
As suggested by Seongbae, selecting the set of all days can get *annoying* if done by every schedule. He comments that it would be good to add a button that selects all weekly days, or a default already selected set of days.

**Comment by zeronone** [comment]
Resolved at cfe3ed6f010f9ed40fbf8bd0cd637d07b86d3548
Also set `start_hour` to `08` and `end_hour` to `20`
