### ISSUE TITLE
Current Schedules time table don't update

### ISSUE THREAD

**Issue by AeroChangmin** [SNUArduinoLabs/coe_control_center#5]
I updated schedules, but the time table in `Current Schedules` on http://localhost:3000/dashboard/schedules don't update.
And on the table, text in the block is schedule description not a schedule name.

**Comment by zeronone** [comment]
Please check now. I have updated the code. If the problem persists, let me know. Thank you

**Comment by zeronone** [comment]
I updated the schedules on my local machine, it seems to get updated on the `Current Schedules` page. I changed the time and dates, they were correctly updated on the `Current Schedules` page too. If there is anything in particular that was not updated, you can let me know.

**Comment by AeroChangmin** [comment]
It's working now 
![screenshot from 2015-09-11 16 37 39](https://cloud.githubusercontent.com/assets/9302086/9809467/5f621b86-58a3-11e5-8bba-da784d089158.png)

![screenshot from 2015-09-11 16 33 41](https://cloud.githubusercontent.com/assets/9302086/9809449/2e0bfeda-58a3-11e5-916c-8cbd9c8e3ef3.png)
But as you can see the notice doesn't follow.
And the edit notice page's title is `Editing Edit`.
Also the button `Update Marquee` looks inactivated, even if I change some contents.

**Comment by zeronone** [comment]
Thank you for the explanation, I will fix it :+1:

**Comment by zeronone** [comment]
I have updated the code. Please take a look.
