### ISSUE TITLE
Adding a new content file never ends

### ISSUE THREAD

**Issue by AeroChangmin** [SNUArduinoLabs/coe_control_center#6]
In `Add a new content` page on `http://localhost:3000/contents/new`, adding a new content file starts immediately after select content file in local. I think it will be better if there is `OK` button.
After the progress bar full, the bar still moving. User can't recognize it is done or not. 
The `Edit Content` page on `http://localhost:3000/contents/#/edit` is same.

**Comment by zeronone** [comment]
Okay, Should I make it similar to uploading the document? Can you check `New Document`. I can make it similar to that.

The reason I did it with the progress bar is that: some video files can be very large and it can take long time. If you want, I can show a message when the upload is completed.

**Comment by AeroChangmin** [comment]
If you show a message, that would be good.

**Comment by zeronone** [comment]
Okay I will show a message after the upload is complete.

**Comment by zeronone** [comment]
I added the message to show that upload has ended.
