### ISSUE TITLE
Lack of way to create new users

### ISSUE THREAD

**Issue by cacyss0807** [SNUArduinoLabs/coe_control_center#7]
Suggestion made by @AeroChangmin:

1. Implement a way to add (create) new users to the control center, through the website.
    * A logged in user should be able to change its password, or if forgotten request a new one to their email (or some other way of password recovery).

2.  Add the username (the one that deploys an schedule) to the schedule JSON that is send to the clients. Maybe, that will let an user know who deployed what schedule.

**Comment by AeroChangmin** [comment]
And a function changing password.

**Comment by zeronone** [comment]
Does it include authorization. Such as some users can upload but not deploy. And some users can deploy?

**Comment by AeroChangmin** [comment]
That's not necessary.

**Comment by cacyss0807** [comment]
Done by @zeronone here 0c84fb68b6c15a54a987aa77af35674b6519ef18
